import Head from 'next/head'
import Header from '../components/header'
import Navbar from '../components/navbar/navbar'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Calendar() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
        <h1 className={styles.title}>
Calendar      </h1>
</main>
    
    </div>
  )
}
