import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/header'
import Navbar from '../components/navbar/navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        
        <title>
          Sailors and Seamen
          </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar/>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <br/>
           The Sailors and SeaMen House
        </h1>

        <p className={styles.description}>
          Fire Island at it's finest.
          
        </p>

        <div className={styles.grid}>
         

          <a href="/about" className={styles.card}>
            <h2>The House &rarr;</h2>
            <p>Things about the house.....</p>
          </a>

          <a href="/rooms" className={styles.card}>
            <h2>Rooms &rarr;</h2>
            <p>Pictures of the rooms</p>
          </a>

          <a
            href="/"
            className={styles.card}
          >
            <h2>Availability &rarr;</h2>
            <p>
              Check Availability
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>History &rarr;</h2>
            <p>Discover about the house</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Directions &rarr;</h2>
            <p>Walk the Boardwalk HENNY</p>
          </a>

          <a
            href="/contact"
            className={styles.card}
          >
            <h2>Contact &rarr;</h2>
            <p>Contact us for booking</p>
          </a>

          <a
            href="/calendar"
            className={styles.card}
          >
            <h2>Calendar &rarr;</h2>
            <p>Let's see when you can stay.</p>
          </a>
        </div>
      </main>

      
    
    </div>
  )
}
